name: CI

# Run on master, tags, or any pull requests
on:
  push:
    branches: [master]
    tags: ["*"]

  pull_request:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 0

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run all tests
        run: go test -v ./...
