name: CI

# Run on master, tags, or any pull requests
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC (8 PM CST)

  push:
    branches: [master]
    tags: ["*"]

  pull_request:

jobs:
  test:
    name: Go - ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      version:
        - "1.19"  # Version originally developed on
        - "1.22"  # Relatively recent version
        - "stable"  # Latest stable version
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
          - x86 # 32-bit; i686
    # env:
      # CGO_ENABLED: 0
    steps:
      - name: Checkout package
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Run all tests
        run: go test -v ./...
